fix: roles management
ForkbombEu/signroom pull request #796
Opened 2024-09-16 10:23 UTC by bbtgnn

2024-09-16 10:23 UTC, bbtgnn commented
@puria let me know what do you think!

2024-09-16 10:40 UTC, puria requested changes
The errors should be i18n translatable, I guess...

2024-09-16 15:00 UTC, bbtgnn commented
@puria done!

2024-09-17 06:15 UTC, bbtgnn commented
@puria locally, i can create an organization without issues. In the tests, it fails for no reason. I don't understand 😭

2024-09-17 14:49 UTC, merged